alias l='ls -l --sort=extension'
alias prune='git fetch --prune origin'
alias c='clear'
alias pep8='pep8 --ignore=E501,E731,E402'

function scrape {
    workon py2
    scrapy crawl levels -s MEMRISE_MIN_LEVEL=1 -s MEMRISE_MAX_LEVEL=$1
    scrapy crawl database -s MEMRISE_SESSION_ID=$2 -s MEMRISE_PAGE_COUNT=$3
}
alias scrape=scrape
